/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_tanners_taggedwallpaper_KeyNDK */

#ifndef _Included_io_tanners_taggedwallpaper_KeyNDK
#define _Included_io_tanners_taggedwallpaper_KeyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_tanners_taggedwallpaper_KeyNDK
 * Method:    getApiKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_tanners_taggedwallpaper_KeyNDK_getApiKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
